version: 2.1
executors:
  linux-2020_01:
    docker:
      - image: cimg/base:2020.01
  linux-stable:
    docker:
      - image: cimg/base:stable
jobs:
  test:
    parameters:
      os:
        type: executor
      java:
        type: string
    executor: << parameters.os >>
    steps:
      - run: echo << parameters.java >> << parameters.os >>
workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux-2020_01, linux-stable]
              java: ["1.8", "17"]