/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package surefire.sub;

import org.junit.Test;

import java.io.IOException;
import java.net.URI;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class LibraryTest {
    private FileSystem fileSystem = initializeFileSystem();

    private FileSystem initializeFileSystem() {
        FileSystem fs = FileSystems.getDefault();
        return fs.provider().getFileSystem(URI.create("file:///"));
    }

    @Test
    public void createTmpDir() throws IOException {
        Path javaTempDir = fileSystem.getPath(System.getProperty("tempDir", System.getProperty("java.io.tmpdir")));
        Files.delete(javaTempDir);
        final Path directory = Files.createDirectory(javaTempDir);
        final String path = directory.toAbsolutePath().toString();
        assertEquals("/tmp", path);
    }
}
