/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package surefire;

import org.junit.Test;

import java.io.IOException;
import java.net.URI;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;

public class LibraryTest {
    private FileSystem fileSystem = initializeFileSystem();

    private FileSystem initializeFileSystem() {
        FileSystem fs = FileSystems.getDefault();
        return fs.provider().getFileSystem(URI.create("file:///"));
    }

    @Test
    public void createTmpDir() throws IOException {
        Path javaTempDir = fileSystem.getPath(System.getProperty("tempDir", System.getProperty("java.io.tmpdir")));
        final Path directory = Files.createDirectories(javaTempDir);
        System.out.println(directory.toAbsolutePath());
    }
}
